name: cloudstation_project_assembler
description: A helper library for assembling CloudStation projects into generated, platform-specific projects.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloudstation_protocols:
    path: ../protocols_dart
