name: cloudstation_event_handler
description: A helper library for handling CloudStation project events and applying them to a project state.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.2.0
  cloudstation_protocols:
    path: ../protocols_dart
